name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Gradle Build Action
      # You may pin to the exact commit or the version.
      # uses: gradle/gradle-build-action@356abb47e7664b5505e25d7997a5a522a17c62d9
        uses: gradle/gradle-build-action@v2.3.0
       
      - name: Build
        run: make
      - name: List files in the repository
        run: |
          find ${{ github.workspace }}
          
      - name: Commit build artefacts
        # You may pin to the exact commit or the version.
        # uses: mutoco/commit-build-artefacts-action@bc4f47c89dddd69bcac4f827fab765c48e9c58b6
        uses: mutoco/commit-build-artefacts-action@0.4.4
    committer_name: # optional, default is Anonymous          
      - run: echo "ğŸ This job's status is ${{ job.status }}."
